version: '3.4'

services:
  client:
    image: vendergas/desafio-frontend:latest
    network_mode: host
    build:
      context: client
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200
  vendergas:
    image: vendergas/desafio-backend:latest
    network_mode: host
    build:
      context: vendergas
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
